### ISSUE TITLE
validate incorrectly throws error.array.value_out_of_min_max_range

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#574] opened 2022-12-07 23:03 UTC
As validate says, the data file has 1 value 0.007827956
Also, as validate says, Object_Statistics/minimum = 0.007827
So everything should be ok, but:

```
validate -t m0154651923f6_2p_cif_gbl.xml
PDS Validate Tool Report
Configuration:
   Version                       3.1.0-SNAPSHOT
   Date                          2022-12-07T22:54:48Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/m0154651923f6_2p_cif_gbl.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/m0154651923f6_2p_cif_gbl.xml
    Begin Content Validation: file:/Users/rchen/Desktop/m0154651923f6_2p_cif_gbl.fit
      ERROR  [error.array.value_out_of_min_max_range]   array 1, location (400, 246):  Value is less than the minimum value in the label (min=0.007827, got=0.007827956).
    End Content Validation: file:/Users/rchen/Desktop/m0154651923f6_2p_cif_gbl.fit
        1 product validation(s) completed
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.array.value_out_of_min_max_range
End of Report
Completed execution in 4043 ms

```

Actually, if I change Object_Statistics/minimum to 0.007826, validate still fails. 0.007820 works. This showed up in a review of GEO's urn:nasa:pds:nearmsi.gbl run by Paul Geissler

[Archive.zip](https://github.com/NASA-PDS/validate/files/10180689/Archive.zip)

**Comment by rchenatjpl** [comment] 2022-12-07 23:07
Same problem with the max:

```
validate -t m0125249036f2_2p_iof_gbl.xml
PDS Validate Tool Report
Configuration:
   Version                       3.1.0-SNAPSHOT
   Date                          2022-12-07T23:06:41Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/m0125249036f2_2p_iof_gbl.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/m0125249036f2_2p_iof_gbl.xml
        1 product validation(s) completed
Summary:
  0 error(s)
  0 warning(s)
  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
End of Report
Completed execution in 3018 ms
```

[Archive.zip](https://github.com/NASA-PDS/validate/files/10180716/Archive.zip)

**Comment by jordanpadams** [comment] 2022-12-08 23:46
duplicate of #529

**Closed as completed by jordanpadams** 2022-12-08 23:46 UTC
Labels: bug, duplicate, needs:triage
