### ISSUE TITLE
Validate throws an error when updating context products

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS-Incubator/validate#1045] opened 2024-10-29 17:45 UTC
### Checked for duplicates

Yes - I have checked

### 🐛 Describe the bug

When I attempted to update the registered context products list using `validate -u`, I noticed that the validator was throwing an error message.

Despite this error message, the validator still claimed that it ran successfully. The `registered_context_products.json` file appears to be unmodified (the modification date is still in the past) It looks like the error may be a server-side issue, but it seems to be a situation that the validator is not correctly handling.

```
% validate -u

PDS Validate Tool Report

Configuration:
   Version     3.5.2
   Date        2024-10-29T17:00:26Z

Parameters:
   Targets                      []
   Severity Level               WARNING
   Recurse Directories          true
   File Filters Used            [*.xml, *.XML]
   Data Content Validation      on
   Product Level Validation     on
   Max Errors                   100000
   Registered Contexts File     /Users/jessestone/bin/validate-3.5.2/resources/registered_context_products.json


org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException: Error from server at https://pds.nasa.gov/services/search: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html. 
...
<REMOVED FOR CONCISENESS>
...
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:692)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:267)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:246)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:255)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:927)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:940)
	at gov.nasa.pds.validate.ValidateLauncher.getLatestJsonContext(ValidateLauncher.java:530)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1696)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1772)

Product Level Validation Results

  PASS: /Users/jessestone/bin/validate-3.5.2/resources/registered_context_products.json
        1 product validation(s) completed

Summary:

  1 product(s)
  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
    1          product(s) total

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
    0          check(s) total


End of Report
Completed execution in 2663 ms

```

### 🕵️ Expected behavior

I expected the validator to complete the context product without emitting any error messages. Failing that, I expected the validator to fail, and not appear to complete.

### 📜 To Reproduce

1. Run `validate -u`
2. Observe the error messages that are emitted

### 🖥 Environment Info

- Version of this software: validate 3.5.2
- Operating System: MacOS 14.6.1
...

### 📚 Version of Software Used

validate 3.5.2

### 🩺 Test Data / Additional context

Full error message for reference:

[fullmessage.txt](https://github.com/user-attachments/files/17561026/fullmessage.txt)

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment] 2024-10-29 17:57
@jstone-psi this has been fixed with the latest SNAPSHOT of Validate. We will have a new tagged version soon.

In the meantime, you can either [download and start using the latest SNAPSHOT](https://github.com/NASA-PDS/validate/releases/tag/v3.6.0-SNAPSHOT), or download the [latest context products JSON here](https://raw.githubusercontent.com/NASA-PDS/validate/refs/heads/main/src/main/resources/util/registered_context_products.json) and replace the JSON file in `resources/registered_context_products.json`

**Comment by jordanpadams** [comment] 2024-10-29 17:57
Duplicate of https://github.com/NASA-PDS/validate/issues/1034

**Closed as completed by jordanpadams** 2024-10-29 17:57 UTC
Labels: bug, duplicate, needs:triage
