### ISSUE TITLE
Update requirement to allow for specifying a subset of schema/schematrons checking the web for the rest

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#513] opened 2022-06-03 23:44 UTC
## 🐛 Describe the bug identified during I&T
Validate provides the following options: 
```
-S,--schematron <schematron files>      Specify schematron files.
...
 -x,--schema <schema files>              Specify schema files.
```
When either/or are provided, and the companion schema/schematron are provided, `validate` may provoke an exception. Or it may behave differently than if not provided. For instance the validation of [pds4-information-model#434](https://github.com/NASA-PDS/pds4-information-model/issues/434) did not yield an expected exception when only the schema was provided. (Test files pointed at the companion release schematron.) 

See execution chain below for specific detail.

## 🥼 Related Test Case(s)
The PDS4 Information Model ticket NASA-PDS/pds4-information-model#487 is only tangentially related, but when `validate` is run against properly configured test files without specifying both schematron and schema files then an expected exception does not appear. (See attached test data.)

## 🔁 : Related issues
NASA-PDS/pds4-information-model#434

---

## ➕ Additional Details
To test, try specifying both `-S` and `-x` individually or together. Although the test file points to the correct schema/schematron, it doesn't appear to correlate a local file with the online file. 

### 📜 To Reproduce
See invocations of validate in the attached report for different combinations and results. 

### 🕵️ Expected behavior

1. An exception or internal error should not result from a valid schema on disk. The `validate` app should look for the schematron online to accompany it.
2. Validate should not behave differently if it accepts one of an on-disk schema/schematron and pass a test that would otherwise result in errors. 
3. If both a schema and a schematron are required together, `validate` should report that both are required if only one is entered. Or it should report that one is missing.
4. Perhaps validate should look at a directory containing both schema or schematron files, if both are required.

### 📚 Version of Software Used
Validate 2.2.0

### 🩺 Test Data / Additional context
Sample test data:
[434_verified_fail.zip](https://github.com/NASA-PDS/validate/files/8836201/434_verified_fail.zip)

Execution chain:
```
# EXAMPLE of providing only schema that passed item unexpectedly
rayl-c01375:434 johnengelke$ validate -t testdata/1I00/AREA_Camelot_1radii.xml -x /sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.xsd 

PDS Validate Tool Report

Configuration:
   Version                       2.2.0
   Date                          2022-06-03T21:30:41Z

Parameters:
   Targets                       [file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml]
   User Specified Schemas        [file:/sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.xsd]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /sourcecode/source/pds/validate-latest/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml
        1 product validation(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 2537 ms

# EXAMPLE of providing schematron only that unexpectedly yielded an exception
rayl-c01375:434 johnengelke$ validate -t testdata/1I00/AREA_Camelot_1radii.xml -S /sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.sch 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:133)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:275)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1333)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1590)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1636)
Caused by: java.lang.NullPointerException
	at gov.nasa.pds.tools.util.VersionInfo.getDirectoryListing(VersionInfo.java:181)
	at gov.nasa.pds.tools.util.VersionInfo.getDirectoryFileNames(VersionInfo.java:171)
	at gov.nasa.pds.tools.util.VersionInfo.getSchemasFromDirectory(VersionInfo.java:123)
	at gov.nasa.pds.tools.label.LabelValidator.createParserIfNeeded(LabelValidator.java:654)
	at gov.nasa.pds.tools.label.LabelValidator.parseAndValidate(LabelValidator.java:423)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelValidationRule.validateLabel(LabelValidationRule.java:298)
	... 12 more

PDS Validate Tool Report

Configuration:
   Version                       2.2.0
   Date                          2022-06-03T21:31:04Z

Parameters:
   Targets                       [file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml]
   User Specified Schematrons    [file:/sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /sourcecode/source/pds/validate-latest/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml
      ERROR  [error.validation.internal_error]   Error executing validationTask: java.lang.NullPointerException
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.internal_error

End of Report
Completed execution in 2660 ms

# EXAMPLE of providing BOTH schema and schematron that resulted in expected error (runs as if on-disk files are not provided)
rayl-c01375:434 johnengelke$ validate -t testdata/1I00/AREA_Camelot_1radii.xml -x /sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.xsd -S /sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.sch 
Error evaluating ((attr{title=...}, ...)) in xsl:variable/@select on line 12665 column 92 
  FORG0001: Invalid date "2020Z" (Wrong delimiter after year)
  In template rule with match="element(Q{[http://pds.nasa.gov/pds4/pds/v1}Time_Coordinates)/element(Q{http://pds.nasa.gov/pds4/pds/v1}start_date_time](http://pds.nasa.gov/pds4/pds/v1%7DTime_Coordinates)/element(Q%7Bhttp://pds.nasa.gov/pds4/pds/v1%7Dstart_date_time))" on line 12660 of 
     invoked by xsl:apply-templates at #12690
  In template rule with match="( element() | text() | comment() | processing-instruction() )" on line 12689 of 
     invoked by xsl:apply-templates at #12690
  In template rule with match="( element() | text() | comment() | processing-instruction() )" on line 12689 of 
     invoked by xsl:apply-templates at #12690
  In template rule with match="( element() | text() | comment() | processing-instruction() )" on line 12689 of 
     invoked by built-in template rule (text-only)
  In template rule with match="/" on line 152 of 
     invoked by xsl:apply-templates at #2151
  In template rule with match="/" on line 152 of 

PDS Validate Tool Report

Configuration:
   Version                       2.2.0
   Date                          2022-06-03T21:31:37Z

Parameters:
   Targets                       [file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml]
   User Specified Schemas        [file:/sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.xsd]
   User Specified Schematrons    [file:/sourcecode/source/pds/model-ontology-14.0.1/ontology/SchemaXML4/PDS4_PDS_1I00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /sourcecode/source/pds/validate-latest/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/System/Volumes/Data/sourcecode/source/pds/test-validations/12-1/pds4-im/434/testdata/1I00/AREA_Camelot_1radii.xml
        1 product validation(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 3087 ms

rayl-c01375:434 johnengelke$
```

### 🖥 System Info
 - OS: Mac OS X Big Sur 
 - Browser Chrome (does not apply)
 - Version 11.6.6 (OS) / 102.0.5005.61 (Chrome) [but this does not apply to this particular issue]

---

**Comment by al-niessner** [comment] 2023-04-17 18:00
@jordanpadams @jpl-jengelke 

The zip file does not contain the schematron nor schema files. When attempting to reproduce the other problem (schematron parse failure) it has gone away. Cannot duplicate the stated conditions nor reported errors. Closing this ticket.

**Comment by jordanpadams** [comment] 2023-04-18 13:43
@al-niessner see attached. when I run the command-line just specifying the PDS core LDDs, it does not go online to look for the MESSENGER LDD and throws an error:

```
$ validate-3.2.0/bin/validate --schematron test_data/PDS4_PDS_1B00.sch
    --schema test_data/PDS4_PDS_1B00.xsd
    --target test_data/odf07155_msgr_11.xml

PDS Validate Tool Report

Configuration:
   Version                       3.2.0
   Date                          2023-04-18T13:42:17Z

Parameters:
   Targets                       [file:/Users/jpadams/test/test_data/odf07155_msgr_11.xml]
   User Specified Schemas        [file:/Users/jpadams/test/test_data/PDS4_PDS_1B00.xsd]
   User Specified Schematrons    [file:/Users/jpadams/test/test_data/PDS4_PDS_1B00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/test/validate-3.2.0/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/test/test_data/odf07155_msgr_11.xml
      ERROR  [error.label.schema]   line 82, 71: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'MESSENGER'.
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.label.schema

End of Report
Completed execution in 3332 ms
```
[test_data.zip](https://github.com/NASA-PDS/validate/files/11262397/test_data.zip)

**Comment by al-niessner** [comment] 2023-04-18 15:28
@jordanpadams 

Yes, this is exactly the bug in #599 making one of the two duplicates. Since #599 has started already, close this ticket and just solve the problem there. I used the XML from here as the test there and download the schema/schematron from the web then changed its version. It really does make this ticket redundant to #599 allowing it to be closed on those grounds.

**Comment by jordanpadams** [comment] 2023-04-18 15:34
duplicate of #599

**Closed as completed by jordanpadams** 2023-04-18 15:34 UTC
Labels: duplicate, enhancement, B14.0, p.wont-have, icebox, i&t.issue
